---
openapi: 3.0.0
info:
   version: 1.3.0
   title: devcheckforcustom open api specification
   description: school API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8005
     description: school
tags:
- name: mano
paths:
   "/mano":
      get:
         tags:
         -  mano
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  mano
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/mano"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      mano:
         type: object
         properties:
            Name:
               type: "string"
               description: Description
            Email:
               type: "string"
               description: Description